title: Dr. Metablog Analysis
description: An analysis of the writings of Vivian de St. Vrain
baseurl: "/drmetablog"
url: "https://lebowitz.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

# Front matter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"